name: CI/CD

on:
  push:
    branches: [main]

jobs:

  friday-job:
    runs-on: ubuntu-latest
    name: Hello Friday!
    outputs:
      new-version: ${{ steps.friday.outputs.version }}
    steps:
      - name: Ask input
        id: friday
        uses: ville-koskela/github-friday1022-action@v1.1.0
        with:
          bump-type: patch
      - name: check output
        run: echo "success was ${{ steps.friday.outputs.success }}"

  build:
    needs: friday-job
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Setup 'node16'
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: install dependencies
        run: |
          npm ci
          npm install -g @vercel/ncc
      - name: pull develop
        run: |
          git merge --ff develop
      - name: build 
        run: ncc build src/index.ts --license license.txt
      - name: Setup Git
        run: |
          git config user.name 'Ville Koskela'
          git config user.email '${{ secrets.EMAIL }}'
      - name: Push build to repo
        run: |
          git add .
          git commit -m "release ${{ needs.friday-job.outputs.new-version }}"
          git push origin main
